// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// finding_stable_matching
List finding_stable_matching(DataFrame r_ex_male, DataFrame r_ex_female);
RcppExport SEXP _StableMarriage_finding_stable_matching(SEXP r_ex_maleSEXP, SEXP r_ex_femaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type r_ex_male(r_ex_maleSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type r_ex_female(r_ex_femaleSEXP);
    rcpp_result_gen = Rcpp::wrap(finding_stable_matching(r_ex_male, r_ex_female));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StableMarriage_finding_stable_matching", (DL_FUNC) &_StableMarriage_finding_stable_matching, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_StableMarriage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
