# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

finding_stable_matching <- function(r_ex_male, r_ex_female) {
    .Call(`_StableMarriage_finding_stable_matching`, r_ex_male, r_ex_female)
}

